name: Build, test, and publish code coverage

on:
  workflow_call:
    inputs:
      fetch-depth:
        required: true
        type: number
      pre-run-function:
        required: false
        type: string
        default: |
          tyras_pre_run ()
          {
            echo 'No pre-run.'
          }
      post-run-function:
        required: false
        type: string
        default: |
          tyras_post_run ()
          {
            echo 'No post-run.'
          }

jobs:
  build_and_test:
    strategy:
      matrix:
        dir: [ data ]
    runs-on: ubuntu-latest
    name: Build and test ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - id: prepare
        name: Prepare ${{ matrix.dir }}
        shell: bash
        run: |
          set -e

          ${{ inputs.pre-run-function }}
          tyras_pre_run '${{ matrix.dir }}'
      
      - id: build
        name: Build ${{ matrix.dir }}
        shell: bash
        run: |
          set -e

          ./scripts/build.sh '${{ matrix.dir }}'
      
      - id: test
        name: Test ${{ matrix.dir }}
        shell: bash
        run: |
          set -e

          ./scripts/test.sh '${{ matrix.dir }}' coverage

      - id: coverage
        name: Upload coverage for '${{ matrix.dir }}'
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.dir }}
          directory: ${{ matrix.dir }}

      - id: finalize
        name: Finalize ${{ matrix.dir }}
        shell: bash
        run: |
          set -e

          ${{ inputs.post-run-function }}
          tyras_post_run '${{ matrix.dir }}'
