name: CI Pipeline

on:
  pull_request:
    branches:
    - main

jobs:
  ci_job:
    uses: ./.github/workflows/build-and-test.yml
    with:
      fetch-depth: 0 # No need to fetch whole history for CI
